#!/usr/bin/env bash
# Inno Setup — LiveVocoder/installer/LiveVocoderCppMinimal.iss → dist-installer/*.exe
set -euo pipefail
# Embedded shell paths — must match installer/LiveVocoderCppMinimal.iss:
#   SetupEmbeddedShPrefix (EMBED_SH), SetupEmbeddedBashPrefix (EMBED_BASH)
: "${EMBED_SH:=/bin/sh}"
: "${EMBED_BASH:=/bin/bash}"
ROOT="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT"
mkdir -p "${ROOT}/dist-installer"

bash "${ROOT}/bundle-installer-minimal.sh"

if ! python3 "${ROOT}/installer/gen_livevocoder_ico.py"; then
  echo "Failed to build installer/LiveVocoder.ico (need python3 + Pillow or ffmpeg)." >&2
  exit 1
fi
if [[ ! -f "${ROOT}/installer/LiveVocoder.ico" ]]; then
  echo "Missing installer/LiveVocoder.ico" >&2
  exit 1
fi

iscc=""
for d in \
  "/c/Program Files (x86)/Inno Setup 6" \
  "/c/Program Files/Inno Setup 6"; do
  if [[ -x "$d/ISCC.exe" ]]; then
    iscc="$d/ISCC.exe"
    break
  fi
done

if [[ -z "$iscc" ]] && command -v iscc.exe >/dev/null 2>&1; then
  iscc="$(command -v iscc.exe)"
fi

if [[ -n "$iscc" ]]; then
  "$iscc" "${ROOT}/installer/LiveVocoderCppMinimal.iss"
else
  _wp="${WINEPREFIX:-$HOME/.wine}"
  _wiscc="$_wp/drive_c/Program Files (x86)/Inno Setup 6/ISCC.exe"
  if [[ -f "$_wiscc" ]] && command -v wine >/dev/null 2>&1; then
    echo "Using Wine: $_wiscc" >&2
    (cd "${ROOT}/installer" && wine "$_wiscc" LiveVocoderCppMinimal.iss)
  else
    echo "ISCC.exe not found. Install Inno Setup 6 or Wine + Inno. See installer/README-INSTALLER.txt" >&2
    exit 1
  fi
fi

echo "Installer output:"
ls -1 "${ROOT}/dist-installer"/LiveVocoder-Setup.exe "${ROOT}/dist-installer"/LiveVocoder_Cpp_Setup_*.exe 2>/dev/null || true

cp -f "${ROOT}/installer/sh-LiveVocoder-Setup.sh" "${ROOT}/dist-installer/sh-LiveVocoder-Setup.sh"
chmod +x "${ROOT}/dist-installer/sh-LiveVocoder-Setup.sh"

_setup_exe="$(ls -1t "${ROOT}/dist-installer"/LiveVocoder-Setup.exe 2>/dev/null | head -1)"
if [[ -z "$_setup_exe" ]]; then
  _setup_exe="$(ls -1t "${ROOT}/dist-installer"/LiveVocoder_Cpp_Setup_*.exe 2>/dev/null | head -1)"
fi
if [[ -n "$_setup_exe" ]]; then
  cp -f "${ROOT}/installer/LiveVocoder.ico" "${ROOT}/dist-installer/LiveVocoder.ico"
  _ic_abs="$(readlink -f "${ROOT}/dist-installer/LiveVocoder.ico")"
  _ex_abs="$(readlink -f "$_setup_exe")"
  _sh_setup="$(readlink -f "${ROOT}/dist-installer/sh-LiveVocoder-Setup.sh")"
  _desk="${ROOT}/dist-installer/LiveVocoder_Cpp_Setup_Wine.desktop"
  # Embedded POSIX shell prefix (/bin/sh), not PATH-dependent "sh". %k = this .desktop path (freedesktop).
  cat >"$_desk" <<DESK1
[Desktop Entry]
Version=1.0
Type=Application
Name=Live Vocoder C++ Setup (minimal)
Comment=Windows installer (embedded /bin/sh prefix → Wine; folder can move with this .desktop)
DESK1
  # %% so printf does not treat % as a format; output must contain literal %k for freedesktop.
  # Use sh-LiveVocoder-Setup.sh (stops running LiveVocoder.exe first — Inno fails with DeleteFile in use otherwise).
  printf 'Exec=%s -c '\''cd "$(dirname "%%k")" && exec ./sh-LiveVocoder-Setup.sh'\''\n' "${EMBED_SH}" >>"$_desk"
  cat >>"$_desk" <<DESK3
TryExec=${EMBED_SH} "${_sh_setup}"
Icon=${_ic_abs}
Categories=AudioVideo;Audio;Mixer;
StartupNotify=true
DESK3
  chmod 755 "$_desk"
  echo "Linux launcher: $_desk" >&2

  _app_launch="${ROOT}/dist-installer/live-vocoder-wine-launch.sh"
  cat >"$_app_launch" <<'LAUNCHEOF'
#!/usr/bin/env bash
# Launch LiveVocoder.exe via Wine with PipeWire virtual mic auto-setup.
# Generated by build-installer-minimal.sh — place next to the Setup .exe or copy anywhere.
set -euo pipefail

SINK_NAME="live_vocoder"
MIC_NAME="${SINK_NAME}_mic"
MON_NAME="${SINK_NAME}.monitor"

WINEPREFIX="${WINEPREFIX:-$HOME/.wine}"
EXE="$WINEPREFIX/drive_c/Program Files/Live Vocoder/LiveVocoder.exe"

if [[ ! -f "$EXE" ]]; then
  echo "LiveVocoder.exe not found at: $EXE" >&2
  echo "Run the Inno Setup installer first:  wine $(dirname "$0")/LiveVocoder_Cpp_Setup_*.exe" >&2
  exit 1
fi

if command -v pactl >/dev/null 2>&1; then
  # Match C++ purge: full teardown of LiveVocoder modules (incl. duplicates), then one stack is recreated below.
  pactl list modules short 2>/dev/null | awk '$2 ~ /loopback/ && index($0,"live_vocoder.monitor"){print $1}' | while read -r id; do [ -n "$id" ] && pactl unload-module "$id" 2>/dev/null || true; done
  pactl list modules short 2>/dev/null | awk '($2=="module-remap-source"||$2=="module-virtual-source")&&(/live_vocoder_mic/||/LiveVocoderVirtualMic/){print $1}' | while read -r id; do [ -n "$id" ] && pactl unload-module "$id" 2>/dev/null || true; done
  pactl list modules short 2>/dev/null | awk '$2=="module-null-sink"&&(/live_vocoder/||/LiveVocoder/){print $1}' | while read -r id; do [ -n "$id" ] && pactl unload-module "$id" 2>/dev/null || true; done
  sleep 0.12
  if ! pactl list short sinks 2>/dev/null | grep -q "$SINK_NAME"; then
    pactl load-module module-null-sink sink_name="$SINK_NAME" \
      rate=48000 channels=2 \
      sink_properties="device.description=LiveVocoder node.description=LiveVocoder media.class=Audio/Sink" \
      2>/dev/null || true
    sleep 0.25
  fi
  for _w2 in $(seq 1 20); do
    pactl list short sources 2>/dev/null | grep -q "$MON_NAME" && break
    sleep 0.1
  done
  if ! pactl list short sources 2>/dev/null | grep -q "$MIC_NAME"; then
    if pactl list short sources 2>/dev/null | grep -q "$MON_NAME"; then
      for _m2 in 1 2 3 4 5; do
        pactl load-module module-remap-source master="$MON_NAME" source_name="$MIC_NAME" \
          source_properties="device.description=LiveVocoderVirtualMic node.description=LiveVocoderVirtualMic \
media.class=Audio/Source/Virtual device.form-factor=microphone" 2>/dev/null || true
        pactl list short sources 2>/dev/null | grep -q "$MIC_NAME" && break
        sleep 0.15
      done
    fi
  fi
fi

export PULSE_SINK="$SINK_NAME"
export LIVE_VOCODER_PULSE_SINK="$SINK_NAME"
export WINE_HOST_XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}"

wine "$EXE" "$@" &
_WINE_PID=$!

_MOVER_PID=""
(
  sleep 3
  for _i in $(seq 1 40); do
    _SI=$(pactl list sink-inputs 2>/dev/null | awk '
      /^Sink Input #[0-9]+/{sub(/^Sink Input #/,"");gsub(/[^0-9].*/,"");sid=$0}
      $0 ~ /application\.name = / && $0 ~ /[Ll]ive[Vv]ocoder|[Ll]ive [Vv]ocoder/ {print sid;exit}
    ' 2>/dev/null || true)
    if [[ -n "$_SI" ]]; then
      _CUR_SINK=$(pactl list sink-inputs 2>/dev/null | awk -v si="$_SI" '
        /^Sink Input #/{sub(/^Sink Input #/,"");gsub(/[^0-9].*/,"");cur=$0}
        /^\tSink:/{if(cur==si){print $2;exit}}
      ' 2>/dev/null || true)
      _TARGET_SINK_ID=$(pactl list short sinks 2>/dev/null | awk -v n="'"$SINK_NAME"'" '$2==n{print $1;exit}' || true)
      if [[ -n "$_TARGET_SINK_ID" ]] && [[ "$_CUR_SINK" != "$_TARGET_SINK_ID" ]]; then
        pactl move-sink-input "$_SI" "$SINK_NAME" 2>/dev/null && break
      else
        break
      fi
    fi
    sleep 0.3
  done
) &
_MOVER_PID=$!

wait "$_WINE_PID" 2>/dev/null || true
if [[ -n "${_MOVER_PID:-}" ]]; then kill "$_MOVER_PID" 2>/dev/null || true; wait "$_MOVER_PID" 2>/dev/null || true; fi
LAUNCHEOF
  chmod +x "$_app_launch"
  echo "Linux app launcher: $_app_launch" >&2

  _app_desk="${ROOT}/dist-installer/LiveVocoder_Wine.desktop"
  _la_abs="$(readlink -f "$_app_launch")"
  {
    echo "[Desktop Entry]"
    echo "Version=1.0"
    echo "Type=Application"
    echo "Name=Live Vocoder"
    echo "Comment=Real-time vocoder (Wine + PipeWire virtual mic)"
    echo "Exec=env PULSE_SINK=live_vocoder LIVE_VOCODER_PULSE_SINK=live_vocoder WINE_HOST_XDG_RUNTIME_DIR=\${XDG_RUNTIME_DIR} ${EMBED_BASH} \"${_la_abs}\" %f"
    echo "Icon=${_ic_abs}"
    echo "Categories=AudioVideo;Audio;Mixer;"
    echo "MimeType=audio/x-wav;audio/mpeg;audio/flac;audio/ogg;"
  } >"$_app_desk"
  chmod 755 "$_app_desk"
  echo "Linux app .desktop: $_app_desk" >&2
fi
